name: athar
description: أثر - استكشف أفضل الأماكن في السعودية
publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - إصدارات محدثة
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  
  # Maps
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_animate: ^4.3.0
  flutter_svg: ^2.0.9
  
  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  
  # Image Handling
  image_picker: ^1.0.5
  
  # State Management
  provider: ^6.1.1
  
  # Utilities
  url_launcher: ^6.2.2
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  dio: ^5.4.0
  crypto: ^3.0.3
  
  # Email Service
  emailjs: ^4.0.0
  
  # 2FA TOTP
  otp: ^3.1.4
  qr_flutter: ^4.1.0
  
  # AdMob
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#A67C52"
  adaptive_icon_foreground: "assets/icons/app_icon_adaptive.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#A67C52"
    theme_color: "#A67C52"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: DGEnab
      fonts:
        - asset: assets/fonts/alfont_com_DGEnab-Regular.ttf
          weight: 900
        - asset: assets/fonts/alfont_com_DGEnab-Regular.ttf
          weight: 800
        - asset: assets/fonts/alfont_com_DGEnab-Regular.ttf
          weight: 700
        - asset: assets/fonts/alfont_com_DGEnab-Regular.ttf
          weight: 600
        - asset: assets/fonts/alfont_com_DGEnab-Regular.ttf
          weight: 500
        - asset: assets/fonts/alfont_com_DGEnab-Regular.ttf
          weight: 400
